import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

export const generateMonthlySummaryPDF = (period: string) => {
  const doc = new jsPDF();
  
  // Header
  doc.setFontSize(20);
  doc.setTextColor(27, 75, 140);
  doc.text('GST Auditor AI', 105, 20, { align: 'center' });
  
  doc.setFontSize(16);
  doc.setTextColor(0, 0, 0);
  doc.text(`Monthly GST Summary - ${period}`, 105, 35, { align: 'center' });
  
  // Summary Data
  doc.setFontSize(12);
  doc.text('Summary:', 20, 50);
  
  const summaryData = [
    ['Total Sales', '₹50,000'],
    ['Total Purchases', '₹40,000'],
    ['Output GST', '₹9,000'],
    ['Input GST', '₹7,200'],
    ['GST Payable', '₹1,800'],
  ];
  
  autoTable(doc, {
    startY: 55,
    head: [['Description', 'Amount']],
    body: summaryData,
    theme: 'striped',
    headStyles: { fillColor: [27, 75, 140] },
  });
  
  // Footer
  doc.setFontSize(10);
  doc.setTextColor(128, 128, 128);
  doc.text('Generated by GST Auditor AI', 105, 280, { align: 'center' });
  doc.text(`Date: ${new Date().toLocaleDateString('en-IN')}`, 105, 285, { align: 'center' });
  
  doc.save(`GST_Summary_${period.replace(/ /g, '_')}.pdf`);
};

export const generateSalesReportPDF = (period: string) => {
  const doc = new jsPDF();
  
  doc.setFontSize(20);
  doc.setTextColor(27, 75, 140);
  doc.text('GST Auditor AI', 105, 20, { align: 'center' });
  
  doc.setFontSize(16);
  doc.setTextColor(0, 0, 0);
  doc.text(`Sales Report - ${period}`, 105, 35, { align: 'center' });
  
  const salesData = [
    ['INV-001', '12-02-2026', 'ABC Traders', '₹1,180', '₹180'],
    ['INV-002', '11-02-2026', 'XYZ Corp', '₹5,900', '₹900'],
    ['INV-003', '10-02-2026', 'Kumar Enterprises', '₹23,600', '₹3,600'],
    ['INV-004', '09-02-2026', 'Sharma & Co', '₹11,800', '₹1,800'],
  ];
  
  autoTable(doc, {
    startY: 45,
    head: [['Invoice', 'Date', 'Customer', 'Amount', 'GST']],
    body: salesData,
    foot: [['', '', 'Total', '₹42,480', '₹6,480']],
    theme: 'striped',
    headStyles: { fillColor: [27, 75, 140] },
    footStyles: { fillColor: [27, 75, 140], fontStyle: 'bold' },
  });
  
  doc.setFontSize(10);
  doc.setTextColor(128, 128, 128);
  doc.text('Generated by GST Auditor AI', 105, 280, { align: 'center' });
  doc.text(`Date: ${new Date().toLocaleDateString('en-IN')}`, 105, 285, { align: 'center' });
  
  doc.save(`Sales_Report_${period.replace(/ /g, '_')}.pdf`);
};

export const generatePurchaseReportPDF = (period: string) => {
  const doc = new jsPDF();
  
  doc.setFontSize(20);
  doc.setTextColor(27, 75, 140);
  doc.text('GST Auditor AI', 105, 20, { align: 'center' });
  
  doc.setFontSize(16);
  doc.setTextColor(0, 0, 0);
  doc.text(`Purchase Report - ${period}`, 105, 35, { align: 'center' });
  
  const purchaseData = [
    ['P-001', '10-02-2026', 'Supplier A', '₹15,000', '₹2,700'],
    ['P-002', '08-02-2026', 'Supplier B', '₹12,000', '₹2,160'],
    ['P-003', '05-02-2026', 'Supplier C', '₹8,000', '₹1,440'],
  ];
  
  autoTable(doc, {
    startY: 45,
    head: [['Invoice', 'Date', 'Supplier', 'Amount', 'GST']],
    body: purchaseData,
    foot: [['', '', 'Total', '₹35,000', '₹6,300']],
    theme: 'striped',
    headStyles: { fillColor: [27, 75, 140] },
    footStyles: { fillColor: [27, 75, 140], fontStyle: 'bold' },
  });
  
  doc.setFontSize(10);
  doc.setTextColor(128, 128, 128);
  doc.text('Generated by GST Auditor AI', 105, 280, { align: 'center' });
  doc.text(`Date: ${new Date().toLocaleDateString('en-IN')}`, 105, 285, { align: 'center' });
  
  doc.save(`Purchase_Report_${period.replace(/ /g, '_')}.pdf`);
};

export const generateGSTRReportPDF = (type: string, period: string) => {
  const doc = new jsPDF();
  
  doc.setFontSize(20);
  doc.setTextColor(27, 75, 140);
  doc.text('GST Auditor AI', 105, 20, { align: 'center' });
  
  doc.setFontSize(16);
  doc.setTextColor(0, 0, 0);
  doc.text(`${type} Summary - ${period}`, 105, 35, { align: 'center' });
  
  doc.setFontSize(12);
  doc.text('Return Details:', 20, 50);
  
  const returnData = type === 'GSTR-1' ? [
    ['Outward Supplies (B2B)', '₹35,000'],
    ['Outward Supplies (B2C)', '₹15,000'],
    ['Total Taxable Value', '₹50,000'],
    ['Total Tax', '₹9,000'],
  ] : [
    ['Total Output Tax', '₹9,000'],
    ['Total Input Tax Credit', '₹7,200'],
    ['Net Tax Payable', '₹1,800'],
    ['Interest', '₹0'],
    ['Late Fee', '₹0'],
  ];
  
  autoTable(doc, {
    startY: 55,
    head: [['Description', 'Amount']],
    body: returnData,
    theme: 'striped',
    headStyles: { fillColor: [27, 75, 140] },
  });
  
  doc.setFontSize(10);
  doc.setTextColor(128, 128, 128);
  doc.text('Generated by GST Auditor AI', 105, 280, { align: 'center' });
  doc.text(`Date: ${new Date().toLocaleDateString('en-IN')}`, 105, 285, { align: 'center' });
  
  doc.save(`${type}_Summary_${period.replace(/ /g, '_')}.pdf`);
};

export const generateAnnualTaxSummaryPDF = (period: string) => {
  const doc = new jsPDF();
  
  doc.setFontSize(20);
  doc.setTextColor(27, 75, 140);
  doc.text('GST Auditor AI', 105, 20, { align: 'center' });
  
  doc.setFontSize(16);
  doc.setTextColor(0, 0, 0);
  doc.text(`Annual Tax Summary - ${period}`, 105, 35, { align: 'center' });
  
  const annualData = [
    ['Total Annual Sales', '₹6,00,000'],
    ['Total Annual Purchases', '₹4,80,000'],
    ['Total Output GST', '₹1,08,000'],
    ['Total Input GST', '₹86,400'],
    ['Net GST Paid', '₹21,600'],
  ];
  
  autoTable(doc, {
    startY: 45,
    head: [['Description', 'Amount']],
    body: annualData,
    theme: 'striped',
    headStyles: { fillColor: [27, 75, 140] },
  });
  
  doc.setFontSize(10);
  doc.setTextColor(128, 128, 128);
  doc.text('Generated by GST Auditor AI', 105, 280, { align: 'center' });
  doc.text(`Date: ${new Date().toLocaleDateString('en-IN')}`, 105, 285, { align: 'center' });
  
  doc.save(`Annual_Tax_Summary_${period.replace(/ /g, '_')}.pdf`);
};
